### ISSUE TITLE
导出word 图片是一个网络连接

### ISSUE THREAD

**Issue by Ytwh** [petterobam/html2file#10]
当导出的word处于离线状态时，图片不会显示出来，我查阅了一下poi的文档，这个好像是他们的bug，不知道有没有办法可以解决这个问题。

**Comment by petterobam** [comment]
这需要写代码编辑word将poi图片引用Image对象下载图片后转成转换成字节图片Image对象替换word里面的内容，这个需要参考poi的图片修改api



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月17日(周四) 下午3:05
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [petterobam/html2file] 导出word 图片是一个网络连接 (#10)




 
当导出的word处于离线状态时，图片不会显示出来，我查阅了一下poi的文档，这个好像是他们的bug，不知道有没有办法可以解决这个问题。
