### ISSUE TITLE
如何跳过刷新的界面

### ISSUE THREAD

**Issue by linxuebo** [petterobam/html2file#14]
我访问一个页面的时候先有刷新才能显示页面，然后我想打印这个页面的时候，只能打印出刷新时候的界面，打印不出最终的页面。请问我应该如何处理呢？

**Comment by petterobam** [comment]
你需要分析最终跳转的页面的 URL 逻辑（可能是调用某个接口获取的跳转链接，重定向跳转分析这个链接的返回值解析重定向的 URL），用最终的 URL 去导出文件。
