### ISSUE TITLE
macbook执行html转图片时报错

### ISSUE THREAD

**Issue by lihaimian** [petterobam/html2file#17]
ERROR>/Users/alex/MyWorkspace/do1/Project/qiqiao2/bpms-runtime/web/target/classes/plugin/linux/wkhtmltox/bin/wkhtmltoimage: /Users/alex/MyWorkspace/do1/Project/qiqiao2/bpms-runtime/web/target/classes/plugin/linux/wkhtmltox/bin/wkhtmltoimage: cannot execute binary file

 在macbook系统上，执行将html文件转换成图片时报以上错误，猜测该错误导致的原因可能与执行的脚本所编译的环境有关

**Comment by petterobam** [comment]
要把 wkhtmltoimage 文件变成可执行文件
