### ISSUE TITLE
在Linux上运行报以下错误，怎么解决？

### ISSUE THREAD

**Issue by sixiwa** [petterobam/html2file#19]
ERROR>Loading pages (1/6)
ERROR>[>                                                           ] 0%
ERROR>[======>                                                     ] 10%
ERROR>QSslSocket: cannot resolve CRYPTO_num_locks
ERROR>QSslSocket: cannot resolve CRYPTO_set_id_callback
ERROR>QSslSocket: cannot resolve CRYPTO_set_locking_callback
ERROR>QSslSocket: cannot resolve sk_free
ERROR>QSslSocket: cannot resolve sk_num
ERROR>QSslSocket: cannot resolve sk_pop_free
ERROR>QSslSocket: cannot resolve sk_value
ERROR>QSslSocket: cannot resolve SSL_library_init
ERROR>QSslSocket: cannot resolve SSL_load_error_strings
ERROR>QSslSocket: cannot resolve SSLv23_client_method
ERROR>QSslSocket: cannot resolve SSLv23_server_method
ERROR>QSslSocket: cannot resolve X509_STORE_CTX_get_chain
ERROR>QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
ERROR>QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
ERROR>QSslSocket: cannot resolve SSLeay
ERROR>QSslSocket: cannot call unresolved function CRYPTO_num_locks
ERROR>QSslSocket: cannot call unresolved function CRYPTO_set_id_callback
ERROR>QSslSocket: cannot call unresolved function CRYPTO_set_locking_callback
ERROR>QSslSocket: cannot call unresolved function SSL_library_init
ERROR>QSslSocket: cannot call unresolved function SSLv23_client_method
ERROR>QSslSocket: cannot call unresolved function sk_num

**Comment by petterobam** [comment]
你机器上的libssl的库版本不对

**Comment by sixiwa** [comment]
> 你机器上的libssl的库版本不对

正确的版本号应该是多少呢？

**Comment by petterobam** [comment]
试下 libssl1.0-dev，太久远了。。
