### ISSUE TITLE
html转word的时候 wps打开word不行

### ISSUE THREAD

**Issue by yuyi2015** [petterobam/html2file#3]
html转word的时候 wps打开doc不行

**Comment by petterobam** [comment]
什么版本的WPS

**Comment by yuyi2015** [comment]
11.1.0.9098-Release 正式版本 附件是我这边根据poi官网生成的样式



chenyijie0525@126.com
 
发件人： petter
发送时间： 2019-09-26 20:28
收件人： petterobam/html2file
抄送： yuyi2015; Author
主题： Re: [petterobam/html2file] html转word的时候 wps打开word不行 (#3)
什么版本的WPS

**Comment by petterobam** [comment]
目前没有发现有这种问题，我在word、linux和mac系统都试过，除了内容有所差异，没有打不开的情况，具体问题可能需要你自己debug看下了，如果解决了欢迎分享案例^_^
