### ISSUE TITLE
在本地试的可以，但是放到服务器上就报错了， HostNotFoundError 咋解决？

### ISSUE THREAD

**Issue by hayye** [petterobam/html2file#4]
![image](https://user-images.githubusercontent.com/30612116/78199693-ffa78b80-74be-11ea-8f50-86aea4c0a981.png)

**Comment by petterobam** [comment]
错误信息里看到你用 http://www.baidu.com 做实验，应该是你的服务器连不了外网

**Comment by linxuebo** [comment]
请问您是如何部署的？  在maven直接package就可以了吗

**Comment by hayye** [comment]
> 请问您是如何部署的？ 在maven直接package就可以了吗

应该是的，不过当时应该都已经解决了，这都两年了，已经没在那儿工作了，也不记得了

**Comment by linxuebo** [comment]
好的，谢谢您
