### ISSUE TITLE
Install出现错误　

### ISSUE THREAD

**Issue by canghaihongxin** [petterobam/html2file#6]
![image](https://user-images.githubusercontent.com/30309837/82881902-e2e57c80-9f72-11ea-8342-3ae72e80872e.png)

报错：
OS=Windows and the assembly descriptor contains a *nix-specific root-relative-reference (starting with slash) /resources
OS=Windows and the assembly descriptor contains a *nix-specific root-relative-reference (starting with slash) /plugins
OS=Windows and the assembly descriptor contains a *nix-specific root-relative-reference (starting with slash) /bin

**Comment by petterobam** [comment]
Windows打包异常，请自行搜索解决：[百度结果](https://www.baidu.com/s?ie=utf-8&f=8&rsv_bp=1&tn=02003390_42_hao_pg&wd=OS%3DWindows%20and%20the%20assembly%20descriptor%20contains%20a%20*nix-specific%20root-relative-reference%20(starting%20with%20slash)%20%2Fresources&oq=OS%253DWindows%2520and%2520the%2520assembly%2520descriptor%2520contains%2520a%2520*nix-specific%2520root-relativ&rsv_pq=cb0f8aa6000013f6&rsv_t=17b21AxDZ%2FrzGPj0zFRGyGOFatHPibXx%2B%2B24q9voNY7WN5tdL47EKzefeZDBRBsJ%2Bl3%2FEorSrqS5&rqlang=cn&rsv_enter=0&rsv_dl=tb&rsv_btype=t&rsv_sug3=6&rsv_sug4=4509)
