### ISSUE TITLE
每次生成PDF文件后，都自动重启

### ISSUE THREAD

**Issue by chenxxx999** [petterobam/html2file#8]
每次生成PDF文件后，都自动重启，我是直接导进idea运行项目，每次生成PDF文件后，控制台都输出项目重启的日志，请问这个有办法解决吗？还是这是正常的

![image](https://user-images.githubusercontent.com/66722412/97102770-3eaf5f80-16e3-11eb-8f54-964261670cdc.png)

**Comment by petterobam** [comment]
你好，这个不是重启，可能是 Spring-Boot 项目本身依赖可能没有下载完等问题，从图中看 “unregister JMX-exposed beans on shutdown” 是一个常见的问题，请借助网络查找下解决方案~

**Comment by zj12346666** [comment]
我也是这问题每次执行完成之后就重启了，你解决了这个问题吗

**Comment by linxuebo** [comment]
我也是出现了这问题，每次生成完pdf之后就自动重启了，你解决了这个问题吗
